CREATE DATABASE IF NOT EXISTS canteen_db;
USE canteen_db;

CREATE TABLE users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 username VARCHAR(50) UNIQUE NOT NULL,
 password VARCHAR(100) NOT NULL,
 role VARCHAR(20) NOT NULL
);

CREATE TABLE food_items (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 category VARCHAR(50) NOT NULL,
 price DOUBLE NOT NULL,
 stock INT NOT NULL
);

CREATE TABLE orders (
 id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT NOT NULL,
 total DOUBLE NOT NULL,
 status VARCHAR(30) NOT NULL DEFAULT 'Placed',
 order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE order_items (
 id INT AUTO_INCREMENT PRIMARY KEY,
 order_id INT NOT NULL,
 food_id INT NOT NULL,
 quantity INT NOT NULL,
 price DOUBLE NOT NULL,
 FOREIGN KEY(order_id) REFERENCES orders(id),
 FOREIGN KEY(food_id) REFERENCES food_items(id)
);

CREATE TABLE bills (
 id INT AUTO_INCREMENT PRIMARY KEY,
 order_id INT NOT NULL,
 amount DOUBLE NOT NULL,
 bill_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(order_id) REFERENCES orders(id)
);
