import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;

public class AdminFrame extends JFrame {
    private final Admin admin; private DefaultTableModel foodModel; private JTable foodTable;
    public AdminFrame(Admin admin){this.admin=admin;setTitle("Admin Dashboard");setSize(1180,720);setLocationRelativeTo(null);setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);build();loadFood();setVisible(true);}
    private void build(){JPanel root=new JPanel(new BorderLayout());root.setBackground(UITheme.BG);JPanel top=new JPanel(new BorderLayout());top.setBackground(UITheme.CARD);top.setBorder(BorderFactory.createEmptyBorder(12,22,12,22));top.add(UITheme.heading("Admin Dashboard • "+admin.getName(),22),BorderLayout.WEST);JPanel actions=new JPanel(new FlowLayout(FlowLayout.RIGHT));actions.setOpaque(false);JButton users=UITheme.button("Users",UITheme.PRIMARY);JButton orders=UITheme.button("Orders",UITheme.PRIMARY);JButton logout=UITheme.button("Logout",UITheme.DANGER);users.addActionListener(e->viewUsers());orders.addActionListener(e->viewOrders());logout.addActionListener(e->{dispose();new LoginFrame();});actions.add(users);actions.add(orders);actions.add(logout);top.add(actions,BorderLayout.EAST);root.add(top,BorderLayout.NORTH);
        JPanel content=new JPanel(new BorderLayout(12,12));content.setBorder(BorderFactory.createEmptyBorder(14,18,18,18));content.setBackground(UITheme.BG);JPanel title=UITheme.card(new BorderLayout());title.add(UITheme.heading("Menu & Stock Management",18),BorderLayout.WEST);JButton refresh=UITheme.button("Refresh",UITheme.PRIMARY);refresh.addActionListener(e->loadFood());title.add(refresh,BorderLayout.EAST);content.add(title,BorderLayout.NORTH);
        foodModel=new DefaultTableModel(new String[]{"ID","Food","Category","Price","Stock"},0){public boolean isCellEditable(int r,int c){return false;}};foodTable=new JTable(foodModel);UITheme.styleTable(foodTable);content.add(new JScrollPane(foodTable),BorderLayout.CENTER);
        JPanel b=new JPanel(new FlowLayout(FlowLayout.LEFT));b.setOpaque(false);JButton add=UITheme.button("Add Food",UITheme.SUCCESS);JButton update=UITheme.button("Update Food",UITheme.WARNING);JButton delete=UITheme.button("Delete Food",UITheme.DANGER);add.addActionListener(e->addFood());update.addActionListener(e->updateFood());delete.addActionListener(e->deleteFood());b.add(add);b.add(update);b.add(delete);content.add(b,BorderLayout.SOUTH);root.add(content,BorderLayout.CENTER);setContentPane(root);}
    private void loadFood(){foodModel.setRowCount(0);try(Connection c=DBConnection.getConnection();Statement s=c.createStatement();ResultSet rs=s.executeQuery("SELECT * FROM food_items ORDER BY id")){while(rs.next())foodModel.addRow(new Object[]{rs.getInt("id"),rs.getString("name"),rs.getString("category"),String.format("%.2f",rs.getDouble("price")),rs.getInt("stock")});}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}}
    private void addFood(){JTextField n=new JTextField(),cat=new JTextField(),pr=new JTextField(),st=new JTextField();JPanel p=form(n,cat,pr,st);if(JOptionPane.showConfirmDialog(this,p,"Add Food",JOptionPane.OK_CANCEL_OPTION)!=JOptionPane.OK_OPTION)return;saveFood(0,n,cat,pr,st,true);}
    private void updateFood(){int r=foodTable.getSelectedRow();if(r<0){JOptionPane.showMessageDialog(this,"Select a food item.");return;}JTextField n=new JTextField(String.valueOf(foodModel.getValueAt(r,1))),cat=new JTextField(String.valueOf(foodModel.getValueAt(r,2))),pr=new JTextField(String.valueOf(foodModel.getValueAt(r,3))),st=new JTextField(String.valueOf(foodModel.getValueAt(r,4)));if(JOptionPane.showConfirmDialog(this,form(n,cat,pr,st),"Update Food",JOptionPane.OK_CANCEL_OPTION)!=JOptionPane.OK_OPTION)return;saveFood((int)foodModel.getValueAt(r,0),n,cat,pr,st,false);}
    private JPanel form(JTextField n,JTextField c,JTextField p,JTextField s){JPanel x=new JPanel(new GridLayout(0,2,8,8));x.add(new JLabel("Name"));x.add(n);x.add(new JLabel("Category"));x.add(c);x.add(new JLabel("Price"));x.add(p);x.add(new JLabel("Stock"));x.add(s);return x;}
    private void saveFood(int id,JTextField n,JTextField cat,JTextField pr,JTextField st,boolean add){try{double price=Double.parseDouble(pr.getText().trim());int stock=Integer.parseInt(st.getText().trim());if(n.getText().trim().isEmpty()||cat.getText().trim().isEmpty()||price<=0||stock<0)throw new Exception("Enter valid values.");try(Connection c=DBConnection.getConnection();PreparedStatement ps=c.prepareStatement(add?"INSERT INTO food_items(name,category,price,stock) VALUES(?,?,?,?)":"UPDATE food_items SET name=?,category=?,price=?,stock=? WHERE id=?")){ps.setString(1,n.getText().trim());ps.setString(2,cat.getText().trim());ps.setDouble(3,price);ps.setInt(4,stock);if(!add)ps.setInt(5,id);ps.executeUpdate();}loadFood();JOptionPane.showMessageDialog(this,add?"Food added successfully.":"Food updated successfully.");}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}}
    private void deleteFood(){int r=foodTable.getSelectedRow();if(r<0)return;int id=(int)foodModel.getValueAt(r,0);if(JOptionPane.showConfirmDialog(this,"Delete selected food?","Confirm",JOptionPane.YES_NO_OPTION)!=JOptionPane.YES_OPTION)return;try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM food_items WHERE id=?")){p.setInt(1,id);p.executeUpdate();loadFood();}catch(Exception e){JOptionPane.showMessageDialog(this,"Cannot delete item already used in orders.");}}
    private void viewUsers(){JDialog d=new JDialog(this,"Registered Users",true);d.setSize(760,460);d.setLocationRelativeTo(this);DefaultTableModel m=new DefaultTableModel(new String[]{"ID","Name","Username","Role"},0){public boolean isCellEditable(int r,int c){return false;}};JTable t=new JTable(m);UITheme.styleTable(t);try(Connection c=DBConnection.getConnection();Statement s=c.createStatement();ResultSet rs=s.executeQuery("SELECT id,name,username,role FROM users ORDER BY id")){while(rs.next())m.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(4)});}catch(Exception e){JOptionPane.showMessageDialog(d,e.getMessage());}d.add(new JScrollPane(t));d.setVisible(true);}
    private void viewOrders(){JDialog d=new JDialog(this,"Order Management",true);d.setSize(980,560);d.setLocationRelativeTo(this);DefaultTableModel m=new DefaultTableModel(new String[]{"Order","Customer","Total","Status","Date"},0){public boolean isCellEditable(int r,int c){return false;}};JTable t=new JTable(m);UITheme.styleTable(t);loadOrders(m);JButton status=UITheme.button("Update Status",UITheme.WARNING);status.addActionListener(e->{int r=t.getSelectedRow();if(r<0)return;String[] opts={"Placed","Preparing","Ready","Completed","Cancelled"};String val=(String)JOptionPane.showInputDialog(d,"Select Status","Status",JOptionPane.PLAIN_MESSAGE,null,opts,m.getValueAt(r,3));if(val==null)return;try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("UPDATE orders SET status=? WHERE id=?")){p.setString(1,val);p.setInt(2,(int)m.getValueAt(r,0));p.executeUpdate();m.setValueAt(val,r,3);}catch(Exception ex){JOptionPane.showMessageDialog(d,ex.getMessage());}});d.add(new JScrollPane(t),BorderLayout.CENTER);d.add(status,BorderLayout.SOUTH);d.setVisible(true);}
    private void loadOrders(DefaultTableModel m){try(Connection c=DBConnection.getConnection();Statement s=c.createStatement();ResultSet rs=s.executeQuery("SELECT o.id,u.name,o.total,o.status,o.order_date FROM orders o JOIN users u ON o.user_id=u.id ORDER BY o.id DESC")){while(rs.next())m.addRow(new Object[]{rs.getInt(1),rs.getString(2),String.format("₹%.2f",rs.getDouble(3)),rs.getString(4),rs.getTimestamp(5)});}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}}
}
