import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;
import java.util.*;

public class CustomerFrame extends JFrame {
    private final Customer customer; private final ArrayList<CartItem> cart=new ArrayList<>(); private final HashMap<Integer,FoodItem> foodMap=new HashMap<>(); private final HashSet<String> categories=new HashSet<>(); private final Hashtable<Integer,CartItem> cartLookup=new Hashtable<>(); private final Object stockMonitor=new Object();
    private DefaultTableModel menuModel,cartModel; private JTable menuTable,cartTable; private JLabel totalLabel,itemsLabel,welcomeLabel; private JComboBox<String> categoryBox; private JTextField searchField;
    public CustomerFrame(Customer customer){this.customer=customer; setTitle("Customer Dashboard");setSize(1180,720);setLocationRelativeTo(null);setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); build(); loadMenu();setVisible(true);}
    private void build(){ JPanel root=new JPanel(new BorderLayout()); root.setBackground(UITheme.BG); root.add(header(),BorderLayout.NORTH); root.add(center(),BorderLayout.CENTER); root.add(cartPanel(),BorderLayout.SOUTH); setContentPane(root); }
    private JPanel header(){ JPanel p=new JPanel(new BorderLayout()); p.setBackground(UITheme.CARD); p.setBorder(BorderFactory.createEmptyBorder(12,22,12,22)); welcomeLabel=UITheme.heading("Hello, "+customer.getName()+" 👋",22); p.add(welcomeLabel,BorderLayout.WEST); JPanel r=new JPanel(new FlowLayout(FlowLayout.RIGHT)); r.setOpaque(false); JButton history=UITheme.button("My Orders",UITheme.PRIMARY); JButton logout=UITheme.button("Logout",UITheme.DANGER); history.addActionListener(e->showOrders()); logout.addActionListener(e->{dispose();new LoginFrame();}); r.add(history);r.add(logout);p.add(r,BorderLayout.EAST); return p; }
    private JPanel center(){ JPanel wrap=new JPanel(new BorderLayout(12,12)); wrap.setBorder(BorderFactory.createEmptyBorder(14,18,10,18)); wrap.setBackground(UITheme.BG); JPanel filters=UITheme.card(new FlowLayout(FlowLayout.LEFT,10,6)); filters.add(UITheme.heading("Food Menu",18)); searchField=new JTextField(18); categoryBox=new JComboBox<>(); categoryBox.addItem("All Categories"); JButton search=UITheme.button("Search",UITheme.PRIMARY); filters.add(new JLabel("Search:"));filters.add(searchField);filters.add(new JLabel("Category:"));filters.add(categoryBox);filters.add(search); search.addActionListener(e->loadMenu()); categoryBox.addActionListener(e->loadMenu()); wrap.add(filters,BorderLayout.NORTH);
        menuModel=new DefaultTableModel(new String[]{"ID","Food Item","Category","Price","Available"},0){public boolean isCellEditable(int r,int c){return false;}}; menuTable=new JTable(menuModel); UITheme.styleTable(menuTable); wrap.add(new JScrollPane(menuTable),BorderLayout.CENTER);
        JPanel actions=new JPanel(new FlowLayout(FlowLayout.RIGHT)); actions.setOpaque(false); JButton add=UITheme.button("Add to Cart",UITheme.SUCCESS); JButton refresh=UITheme.button("Refresh Menu",UITheme.PRIMARY); add.addActionListener(e->addToCart());refresh.addActionListener(e->loadMenu()); actions.add(refresh);actions.add(add);wrap.add(actions,BorderLayout.SOUTH); return wrap; }
    private JPanel cartPanel(){ JPanel p=UITheme.card(new BorderLayout(10,10)); p.setBorder(BorderFactory.createCompoundBorder(new javax.swing.border.EmptyBorder(0,18,18,18),p.getBorder())); JPanel title=new JPanel(new BorderLayout()); title.setOpaque(false); title.add(UITheme.heading("Shopping Cart",18),BorderLayout.WEST); itemsLabel=UITheme.muted("0 items");title.add(itemsLabel,BorderLayout.EAST);p.add(title,BorderLayout.NORTH); cartModel=new DefaultTableModel(new String[]{"Food","Price","Qty","Total"},0){public boolean isCellEditable(int r,int c){return false;}}; cartTable=new JTable(cartModel); UITheme.styleTable(cartTable); cartTable.setPreferredScrollableViewportSize(new Dimension(100,140)); p.add(new JScrollPane(cartTable),BorderLayout.CENTER); JPanel foot=new JPanel(new BorderLayout()); foot.setOpaque(false); JPanel left=new JPanel(new FlowLayout(FlowLayout.LEFT)); left.setOpaque(false); JButton modify=UITheme.button("Modify",UITheme.WARNING); JButton remove=UITheme.button("Remove",UITheme.DANGER); JButton clear=UITheme.button("Clear Cart",new Color(100,110,130)); modify.addActionListener(e->modifyCart());remove.addActionListener(e->removeCart());clear.addActionListener(e->{cart.clear();cartLookup.clear();refreshCart();}); left.add(modify);left.add(remove);left.add(clear);foot.add(left,BorderLayout.WEST); JPanel right=new JPanel(new FlowLayout(FlowLayout.RIGHT));right.setOpaque(false); totalLabel=UITheme.heading("Total: ₹0.00",20); JButton place=UITheme.button("Place Order",UITheme.SUCCESS); place.addActionListener(e->placeOrder());right.add(totalLabel);right.add(place);foot.add(right,BorderLayout.EAST);p.add(foot,BorderLayout.SOUTH); return p; }
    private void loadMenu(){ menuModel.setRowCount(0);foodMap.clear();categories.clear(); String search=searchField==null?"":searchField.getText().trim();String cat=categoryBox==null?"All Categories":String.valueOf(categoryBox.getSelectedItem()); try(Connection c=DBConnection.getConnection();PreparedStatement ps=c.prepareStatement("SELECT * FROM food_items WHERE name LIKE ? AND (?='All Categories' OR category=?) ORDER BY name")){ps.setString(1,"%"+search+"%");ps.setString(2,cat);ps.setString(3,cat);try(ResultSet rs=ps.executeQuery()){while(rs.next()){FoodItem f=new FoodItem(rs.getInt("id"),rs.getString("name"),rs.getString("category"),rs.getDouble("price"),rs.getInt("stock"));foodMap.put(f.getId(),f);categories.add(f.getCategory());menuModel.addRow(new Object[]{f.getId(),f.getName(),f.getCategory(),String.format("₹%.2f",f.getPrice()),f.getStock()});}}}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}
        if(categoryBox!=null){String current=String.valueOf(categoryBox.getSelectedItem());categoryBox.removeAllItems();categoryBox.addItem("All Categories");ArrayList<String> sorted=new ArrayList<>(categories);Collections.sort(sorted);for(String s:sorted)categoryBox.addItem(s); if(current!=null){for(int i=0;i<categoryBox.getItemCount();i++)if(categoryBox.getItemAt(i).equals(current)){categoryBox.setSelectedIndex(i);break;}}}
    }
    private void addToCart(){int row=menuTable.getSelectedRow();if(row<0){JOptionPane.showMessageDialog(this,"Select a food item.");return;}int id=(int)menuModel.getValueAt(row,0);FoodItem f=foodMap.get(id);String s=JOptionPane.showInputDialog(this,"Quantity:","1");if(s==null)return;try{int q=Integer.parseInt(s);if(q<=0)throw new NumberFormatException();CartItem existing=cartLookup.get(id);int next=(existing==null?0:existing.getQuantity())+q;if(next>f.getStock()){JOptionPane.showMessageDialog(this,"Only "+f.getStock()+" available.");return;}if(existing==null){existing=new CartItem(f,q);cart.add(existing);cartLookup.put(id,existing);}else existing.setQuantity(next);refreshCart();}catch(NumberFormatException e){JOptionPane.showMessageDialog(this,"Enter a valid quantity.");}}
    private void modifyCart(){int row=cartTable.getSelectedRow();if(row<0){JOptionPane.showMessageDialog(this,"Select a cart item.");return;}CartItem item=cart.get(row);String s=JOptionPane.showInputDialog(this,"New quantity:",item.getQuantity());if(s==null)return;try{int q=Integer.parseInt(s);if(q<=0||q>item.getFood().getStock())throw new NumberFormatException();item.setQuantity(q);refreshCart();}catch(NumberFormatException e){JOptionPane.showMessageDialog(this,"Invalid quantity.");}}
    private void removeCart(){int row=cartTable.getSelectedRow();if(row<0)return;CartItem item=cart.remove(row);cartLookup.remove(item.getFood().getId());refreshCart();}
    private void refreshCart(){cartModel.setRowCount(0);double total=0;Iterator<CartItem> it=cart.iterator();int count=0;while(it.hasNext()){CartItem x=it.next();double t=x.getTotal();total+=t;count+=x.getQuantity();cartModel.addRow(new Object[]{x.getFood().getName(),String.format("₹%.2f",x.getFood().getPrice()),x.getQuantity(),String.format("₹%.2f",t)});}itemsLabel.setText(count+" item(s)");totalLabel.setText(String.format("Total: ₹%.2f",total));}
    private void placeOrder(){if(cart.isEmpty()){JOptionPane.showMessageDialog(this,"Cart is empty.");return;}double total=0;for(CartItem x:cart)total+=x.getTotal();int ok=JOptionPane.showConfirmDialog(this,String.format("Confirm order for ₹%.2f?",total),"Place Order",JOptionPane.YES_NO_OPTION);if(ok!=JOptionPane.YES_OPTION)return;ArrayList<CartItem> copy=new ArrayList<>();for(CartItem x:cart)copy.add(new CartItem(x.getFood(),x.getQuantity()));OrderWorker worker=new OrderWorker(copy,total);worker.setPriority(Thread.NORM_PRIORITY+1);worker.start();}
    private class OrderWorker extends Thread { private final ArrayList<CartItem> items; private final double total; OrderWorker(ArrayList<CartItem> i,double t){items=i;total=t;} public void run(){ synchronized(stockMonitor){try{if(Thread.currentThread().isInterrupted()) stockMonitor.wait();}catch(InterruptedException ignored){} try(Connection c=DBConnection.getConnection()){c.setAutoCommit(false);try{for(CartItem item:items){try(PreparedStatement p=c.prepareStatement("SELECT stock FROM food_items WHERE id=? FOR UPDATE")){p.setInt(1,item.getFood().getId());try(ResultSet rs=p.executeQuery()){if(!rs.next())throw new Exception("Food not found");if(item.getQuantity()>rs.getInt(1))throw new InsufficientStockException("Insufficient stock for "+item.getFood().getName());}}}int orderId;try(PreparedStatement p=c.prepareStatement("INSERT INTO orders(user_id,total,status) VALUES(?,?,?)",Statement.RETURN_GENERATED_KEYS)){p.setInt(1,customer.getId());p.setDouble(2,total);p.setString(3,"Placed");p.executeUpdate();try(ResultSet k=p.getGeneratedKeys()){k.next();orderId=k.getInt(1);}}for(CartItem item:items){try(PreparedStatement oi=c.prepareStatement("INSERT INTO order_items(order_id,food_id,quantity,price) VALUES(?,?,?,?)");PreparedStatement st=c.prepareStatement("UPDATE food_items SET stock=stock-? WHERE id=?")){oi.setInt(1,orderId);oi.setInt(2,item.getFood().getId());oi.setInt(3,item.getQuantity());oi.setDouble(4,item.getFood().getPrice());oi.executeUpdate();st.setInt(1,item.getQuantity());st.setInt(2,item.getFood().getId());st.executeUpdate();}}try(PreparedStatement b=c.prepareStatement("INSERT INTO bills(order_id,amount) VALUES(?,?)")){b.setInt(1,orderId);b.setDouble(2,total);b.executeUpdate();}c.commit();stockMonitor.notifyAll();final int id=orderId;SwingUtilities.invokeLater(()->{cart.clear();cartLookup.clear();refreshCart();loadMenu();showInvoice(id,total,items);});}catch(Exception ex){c.rollback();throw ex;}}catch(Exception ex){SwingUtilities.invokeLater(()->JOptionPane.showMessageDialog(CustomerFrame.this,"Order failed:\n"+ex.getMessage()));}}}}
    private void showInvoice(int orderId,double total,ArrayList<CartItem> items){StringBuilder sb=new StringBuilder();sb.append("CANTEEN INVOICE\n\nOrder ID: ").append(orderId).append("\nCustomer: ").append(customer.getName()).append("\n\nItems\n");for(CartItem x:items)sb.append(x.getFood().getName()).append(" x ").append(x.getQuantity()).append(" = ₹").append(String.format("%.2f",x.getTotal())).append('\n');sb.append("\nTOTAL BILL = ₹").append(String.format("%.2f",total));JTextArea area=new JTextArea(sb.toString());area.setEditable(false);area.setFont(new Font("Monospaced",Font.PLAIN,14));JOptionPane.showMessageDialog(this,new JScrollPane(area),"Payment Successful",JOptionPane.INFORMATION_MESSAGE);}
    private void showOrders(){JDialog d=new JDialog(this,"My Orders",true);d.setSize(850,500);d.setLocationRelativeTo(this);DefaultTableModel m=new DefaultTableModel(new String[]{"Order ID","Total","Status","Date"},0){public boolean isCellEditable(int r,int c){return false;}};JTable t=new JTable(m);UITheme.styleTable(t);try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("SELECT id,total,status,order_date FROM orders WHERE user_id=? ORDER BY id DESC")){p.setInt(1,customer.getId());try(ResultSet rs=p.executeQuery()){while(rs.next())m.addRow(new Object[]{rs.getInt(1),String.format("₹%.2f",rs.getDouble(2)),rs.getString(3),rs.getTimestamp(4)});}}catch(Exception e){JOptionPane.showMessageDialog(d,e.getMessage());}JButton cancel=UITheme.button("Cancel Selected Order",UITheme.DANGER);cancel.addActionListener(e->{int r=t.getSelectedRow();if(r<0)return;String st=String.valueOf(m.getValueAt(r,2));if(!st.equals("Placed")){JOptionPane.showMessageDialog(d,"Only Placed orders can be cancelled.");return;}int id=(int)m.getValueAt(r,0);cancelOrder(id,m,r,d);});d.add(new JScrollPane(t),BorderLayout.CENTER);d.add(cancel,BorderLayout.SOUTH);d.setVisible(true);}
    private void cancelOrder(int id,DefaultTableModel m,int row,JDialog d){synchronized(stockMonitor){try(Connection c=DBConnection.getConnection()){c.setAutoCommit(false);try(PreparedStatement q=c.prepareStatement("SELECT food_id,quantity FROM order_items WHERE order_id=?")){q.setInt(1,id);try(ResultSet rs=q.executeQuery()){while(rs.next()){try(PreparedStatement u=c.prepareStatement("UPDATE food_items SET stock=stock+? WHERE id=?")){u.setInt(1,rs.getInt(2));u.setInt(2,rs.getInt(1));u.executeUpdate();}}}}try(PreparedStatement u=c.prepareStatement("UPDATE orders SET status='Cancelled' WHERE id=?")){u.setInt(1,id);u.executeUpdate();}c.commit();stockMonitor.notifyAll();m.setValueAt("Cancelled",row,2);loadMenu();JOptionPane.showMessageDialog(d,"Order cancelled.");}catch(Exception e){JOptionPane.showMessageDialog(d,e.getMessage());}}}
}
